[package]
name = "market_data_aggregator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
rand_chacha = "0.3"



[[bin]]
name = "market_data_aggregator"
path = "main.rs"
